### ISSUE TITLE
(Already loaded) translation data gets overridden by other files that get loaded after it.

### ISSUE THREAD

**Issue by david-d-h** [distantmagic/resonance#3]
An issue I've discovered is that when loading translations, only the last file (in alphabetical order) gets loaded. If previously loaded data existed it will be replaced every time a new translation file is loaded. As an example, assume the following file structure.
```ini
# lang/en/website.ini
[error]
bad_request = "Bad request"
```
```ini
# lang/en/z.ini
# this is empty on purpose
```
Now because the letter `z` obviously comes after the letter `w`, it will be loaded after `website.ini`. Which because of this issue means that there are no translations at all.
<details>
    <summary>dump of TranslatorBridge->translations after every individual load of a translation file.</summary>

    // website.ini gets loaded

    object(Ds\Map)#298 (1) {
      [0]=>
      object(Ds\Pair)#755 (2) {
        ["key"]=>
        string(2) "en"
        ["value"]=>
        object(Ds\Map)#757 (1) {
          [0]=>
          object(Ds\Pair)#763 (2) {
            ["key"]=>
            string(17) "error.bad_request"
            ["value"]=>
            string(11) "Bad request"
          }
        }
      }
    }

    // z.ini gets loaded

    object(Ds\Map)#298 (1) {
      [0]=>
      object(Ds\Pair)#757 (2) {
        ["key"]=>
        string(2) "en"
        ["value"]=>
        object(Ds\Map)#763 (0) {
        }
      }
    }
</details>

---

I've also noticed that in the documentation for translations, each file gets their own kind of "namespace" of translations. So with this file:
```ini
# lang/en/website.ini
greeting = "Hello"
```
You should translate `greeting` by doing `TranslatorBridge::trans($request, 'website.greeting');` however this does not work, the translation is simply stored as `'greeting'` without any reference to the original `website` "namespace".

The reason I included this in the issue, is because this "namespacing" could be a solution to both problems.

**Comment by mcharytoniuk** [comment]
Fixed in `v0.11.1`
