### ISSUE TITLE
Docs suggestion - installation and requirements

### ISSUE THREAD

**Issue by malzag** [distantmagic/resonance#4]
In https://resonance.distantmagic.com/docs/getting-started/installation-and-requirements.html, I think it would make more sense to explicitly say that a SSL certificate is needed to run the HTTP server successfully.

Also, there's a typo at the very beginning of that page - see the attached screenshot. 
![screen-1](https://github.com/distantmagic/resonance/assets/12105347/a9f99fd1-d4e9-4468-bb75-91efc900b7ac)

**Comment by mcharytoniuk** [comment]
Thanks!
